test-warnings: no
strictness: medium
autodetect: yes
ignore-patterns:
    - examples/*
    - test/*
    - docs/*
    - tools/*

pylint:
  disable:
  - too-many-arguments
  - too-many-locals
  - too-many-branches

pyflakes:
  disable:
  - F841

mccabe:
  disable:
  - MC0001
