test-warnings: no
strictness: medium
autodetect: yes
ignore-patterns:
    - examples/*
    - test/*
    - docs/*
    - tools/*

pylint:
  disable:
  - too-many-arguments
  - too-many-local-variables
  - too-many-branches

mccabe:
  disable:
  - MC0001
