[workspace]
name = "pycbc"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
c-compiler = "*"
cxx-compiler = "*"
gsl = "*"
mysqlclient = "*"
blas = { version = "*", build = "*openblas" }
fftw = "*"
pytest = "*"

[feature.bbhx.dependencies]
liblapacke = "*"
openblas = "*"

[tasks]
test-unittest = "pytest"
test-help = { cmd = "bash tools/pycbc_test_suite.sh", env = { PYCBC_TEST_TYPE = "help" } }
test-search = { cmd = "bash tools/pycbc_test_suite.sh", env = { PYCBC_TEST_TYPE = "search" } }
test-inference = { cmd = "bash tools/pycbc_test_suite.sh", env = { PYCBC_TEST_TYPE = "inference" } }
test-docs = { cmd = "bash tools/pycbc_test_suite.sh", env = { PYCBC_TEST_TYPE = "docs" } }

[pypi-dependencies]
pycbc = { path = ".", editable = true }
astropy = ">=2.0.3"
Mako = ">=1.0.1"
scipy = ">=0.16.0,<1.17.0"
matplotlib = ">=2.0.0"
numpy = ">=1.16.0"
pillow = "*"
h5py = ">=3.0.0"
jinja2 = "*"
mpld3 = ">=0.3"
beautifulsoup4 = ">=4.6.0"
cython = "*"
lalsuite = "*"
lscsoft-glue = ">=1.59.3"
igwn-segments = "*"
tqdm = "*"
gwdatafind = ">=1.1.3"
pegasus-wms = ">=5.1.1"
boto3 = "*"
certifi = "*"
GitPython = "*"
pyjwt = "*"
pyyaml = "*"
s3transfer = "*"
urllib3 = "*"
markupsafe = "<=2.0.1"
igwn-ligolw = ">=2.1.0"
emcee = "==2.2.1"
dynesty = "<3.0"
Sphinx = ">=4.2.0,<8.2.0"
sphinx-carousel = "*"
sphinx-rtd-theme = ">=1.0.0"
sphinxcontrib-programoutput = ">=0.11"
sphinx_design = "*"
pykerr = "*"
healpy = "*"
ligo-gracedb = ">=2.10.0"
ligo-skymap = ">=2.1.1"
epsie = ">=1.0"
cpnest = "*"
pymultinest = "*"
ultranest = "*"
torch = "*"
nessai = ">=0.11.0"
snowline = "*"
setproctitle = "*"
sympy = ">=1.9"
scikit-learn = "*"
[dependencies]
graphviz = "*"

[environments]
py311 = ["py311"]
py312 = ["py312"]
py313 = ["py313"]
py311-search = ["py311", "search"]
py312-search = ["py312", "search"]
py313-search = ["py313", "search"]
py311-docs = ["py311", "docs", "bbhx"]
py312-docs = ["py312", "docs", "bbhx"]
py313-docs = ["py313", "docs", "bbhx"]

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]

[feature.py313.dependencies]
python = "3.13.*"

[feature.search.dependencies]
mpi4py = "*"

[feature.docs.dependencies]
mpi4py = "*"

[feature.docs.target.linux-64.pypi-dependencies]
cupy-cuda12x = "*"
