#!/usr/bin/python
# Copyright (C) 2011 Karsten Wiesner
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


#
# =============================================================================
#
#                                   Preamble
#
# =============================================================================
#

"""
script patches the proxy class definition that is generated by swig
with one more baseclass that can be defined in the python layer
"""

import sys,re

filetopatch = sys.stdin.readlines();

cnt = 0
for l in filetopatch:
    l = l.rstrip("\n")
    if re.match("^class %s\(_object\):$" % sys.argv[1], l):
        print "from %s import %s" % (sys.argv[2], sys.argv[3])
        print "class %s(%s, _object):" % (sys.argv[1], sys.argv[3])
        cnt += 1
    else:
        print l

sys.exit(cnt != 1)

