#!/bin/env python
import argparse, shutil

parser = argparse.ArgumentParser()
parser.add_argument('--input-file')
parser.add_argument('--output-file')
args = parser.parse_args()

shutil.copyfile(args.input_file, args.output_file)
