#!/bin/env python
import argparse, shutil

parser = argparse.ArgumentParser()
parser.add_argument('--input-file')
parser.add_argument('--output-file')
parser.add_argument("--append-count", type=int, default=1)
parser.add_argument('--append-text', help='append this text to output file')
args = parser.parse_args()

shutil.copyfile(args.input_file, args.output_file)

if args.append_text:
    with open(args.output_file, 'a') as f:
        for i in range(args.append_count):
            f.write(args.append_text)
