name: Install system packages
description: "Composite action to install common system packages (fftw3, intel-mkl, mpi, graphviz) on Ubuntu runners."

runs:
  using: 'composite'
  steps:
    - name: Update apt
      run: |
        sudo apt-get -o Acquire::Retries=3 update

    - name: Install system packages
      run: |
        set -euxo pipefail
        sudo apt-get -o Acquire::Retries=3 install -y *fftw3* intel-mkl* mpi graphviz
