#! /usr/bin/python

from jinja2 import Environment, FileSystemLoader

# initializations
#input_path = '/home/cbiwer/pycbc/ncoinc4_20141124_8e603_working/lib/python2.6/site-packages/pycbc/results/templates/'
input_path = '/home/cbiwer/projects/pycbc_plotting/make_static_html/templates/'
input_template = 'test.html'
output_filename = '/home/cbiwer/public_html/render_template_test.html'

# render template to string
env = Environment(loader=FileSystemLoader(input_path))
template = env.get_template(input_template)

env.globals['STATIC_URL'] = '/home/cbiwer/pycbc/ncoinc4_20141124_8e603_working/lib/python2.6/site-packages/pycbc/results/static/'

context = {'foo' : 'bar'}

output = template.render(context)

# save
with open(output_filename, "wb") as fp:
    fp.write(output)
