#! /usr/bin/python

"""
Simple script to plot a txt file created by a TimeSeries.
"""

import matplotlib as mpl; mpl.use('Agg')
import matplotlib.pyplot as plt
import sys

from pycbc import types

frame_cache = lal.Cache.fromfilenames([sys.argv[1]])
frame_filenames = [entry.path for entry in frame_cache]

#timeseries = types.load_timeseries(sys.argv[1])
timeseries = frame.read_frame(frame_filenames, channel_name, start_time=sys.argv[3], end_time=sys.argv[4])

start = 95
sample_rate = 16384
t0 = start*sample_rate

frequencyseries = timeseries.to_frequencyseries()

plt.loglog(frequencyseries.sample_frequencies, frequencyseries.numpy())
plt.xlim(10,1000)
plt.savefig(sys.argv[2])
