#! /usr/bin/python

import argparse
import logging
import matplotlib as mpl; mpl.use('Agg')
import matplotlib.pyplot as plt
import sys

from glue import lal
from pycbc import frame
from pycbc import types

# initializations
channel_name = sys.argv[1]

# setup log
logging_level = logging.DEBUG
logging.basicConfig(format='%(asctime)s : %(message)s', level=logging_level)

# read frame cache
logging.info('Reading cache file...')
frame_cache = lal.Cache.fromfilenames([sys.argv[2]])
frame_filenames = [entry.path for entry in frame_cache]

# get channel data from frame files
logging.info('Reading frame files...')
data = frame.read_frame(frame_filenames, channel_name, start_time=sys.argv[3], end_time=sys.argv[4])
data.save('output/frame.txt')

# get filtered data from txt file
timeseries = types.load_timeseries(sys.argv[6])

start = 95
sample_rate = 16384
t0 = start*sample_rate

diff = ( data.numpy() - timeseries.numpy()[t0:] ) * data.numpy() * 100

# plot
timeseries = types.load_timeseries('output/test.txt')
plt.plot(data.sample_times, diff, label="100*(f-p)/f")
plt.savefig(sys.argv[5])
