#! /usr/bin/python

import argparse
import ctypes
import logging
from glue import lal
from glue import segments
from pycbc import frame
from pycbc import types

import ROOT
ROOT.gSystem.Load('/usr/lib64/libdmtsigp.so')
ROOT.gSystem.Load('/usr/lib64/libgdsplot.so')
from foton import FilterFile, Filter

# parse command line
parser = argparse.ArgumentParser(usage='pycbc_check_bits [--options]',
                  description='Displays information about filters in filterban.')
parser.add_argument("--filter-file", type=str, required=True,
                  help="Path to foton filter file to extract filterbanks.")
parser.add_argument("--filterbank-name", type=str, required=True,
                  help="Name of the filterbank.")
opts = parser.parse_args()

# setup log
logging_level = logging.DEBUG
logging.basicConfig(format='%(asctime)s : %(message)s', level=logging_level)

# get filter files
logging.info('Reading filter file...')
filter_file = FilterFile(opts.filter_file)

for bit in range(10):

    print opts.filterbank_name, bit, Filter(filter_file[opts.filterbank_name][bit]).design.name
    print Filter(filter_file[opts.filterbank_name][bit]).sections

print dir(Filter(filter_file[opts.filterbank_name][bit]).design)
print dir(Filter(filter_file[opts.filterbank_name][bit]))
print Filter(filter_file[opts.filterbank_name][bit]).sections
