#! /usr/bin/python

import argparse
import ctypes
import logging
from glue import lal
from glue import segments
from pycbc import frame
from pycbc import types
from pycbc.filter.zpk import filter_zpk

import ROOT
ROOT.gSystem.Load('/usr/lib64/libdmtsigp.so')
ROOT.gSystem.Load('/usr/lib64/libgdsplot.so')
from foton import FilterFile, Filter

# parse command line
parser = argparse.ArgumentParser(usage='pycbc_calibrate_data [--options]',
                  description='Read the detector data and applies filters to calibrate the data.')
parser.add_argument("--gps-start-time", type=int, required=True,
                  help="Time to begin filtering input data.")
parser.add_argument("--gps-end-time", type=int, required=True,
                  help="Time to finish filtering input data.")
parser.add_argument("--frame-cache", type=str, required=True,
                  help="Path to frame cache that contains data.")
parser.add_argument("--filter-file", type=str, required=True,
                  help="Path to foton filter file to extract filterbanks.")
opts = parser.parse_args()

# initializations
channel_names = []
channel_names += ['L1:CAL-DARM_ERR_WHITEN_OUT_DQ']

# setup log
logging_level = logging.DEBUG
logging.basicConfig(format='%(asctime)s : %(message)s', level=logging_level)

# read frame cache
logging.info('Reading cache file...')
frame_cache = lal.Cache.fromfilenames([opts.frame_cache])
frame_filenames = [entry.path for entry in frame_cache]

# get channel data from frame files
logging.info('Reading frame files...')
data = frame.read_frame(frame_filenames, channel_names, start_time=opts.gps_start_time, end_time=opts.gps_end_time)

# get filter files
logging.info('Reading filter files...')
filter_file = FilterFile(opts.filter_file)

# put data into arrays
logging.info('ZPK filtering...')
darm_in1 = filter_zpk(data[0], [100.]*5, [1.]*5, 1e-10)

darm_in1 = filter_zpk(darm_in1, [400.], [7000.], -1.)
darm_in1 = filter_zpk(darm_in1, [], [], 1.5e-12)
darm_in1 = filter_zpk(darm_in1, [1.]*5, [100.]*5, 1.)

darm_in1.save('output/zpk.txt')

# DESIGN   CAL_SUM_DARM_ERR 0 zpk([400],[7000],-1,"n")
# DESIGN   CAL_SUM_DARM_ERR 4 gain(1.5e-12)
# DESIGN   CAL_SUM_DARM_ERR 9 zpk([1;1;1;1;1],[100;100;100;100;100],1,"n") \
