[sampler]
name = nessai
nlive = 2000
importance_nested_sampler = True
min_samples = 100
max_iteration = 5

; Other arguments (see the nessai package for details).
; min_remove, draw_constant, reset_flow
