#! /usr/bin/env python
import os
import logging
import configparser as ConfigParser
import argparse

parser = argparse.ArgumentParser(usage='',
    description="Creating injeciton file")
parser.add_argument('--config')
parser.add_argument('--output-file',  help='output xml file iwth the injections')
(options, args) = parser.parse_args()

def get_ini_opts(confs, section):
    op_str = ""
    for opt in confs.options(section):
        val = confs.get(section, opt)
        op_str += "--" + opt + " " + val + " \\" + "\n"
    return op_str

confs = ConfigParser.ConfigParser()
confs.read(options.config)

logging.info("Creating injection file")
inj_str = "lalapps_inspinj " + get_ini_opts(confs, "inspinj") + "--output "+args.output_file
os.system(inj_str)
