name: macos basic tests

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [macos-latest]
        environment: [py311, py312, py313]

    steps:
    - uses: actions/checkout@v5

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        environments: ${{ matrix.environment }}

    - name: Run basic pycbc test suite
      run: |
        pixi run -e ${{ matrix.environment }} test-unittest
