#!/bin/bash
set -e

# Redirect stdout ( > ) into a named pipe ( >() ) running "tee"
exec > >(tee install.log)
exec 2>&1

PEG_DIR=`python -c 'import Pegasus, os.path;print os.path.dirname(Pegasus.__path__[0])'`
export LOCAL=$1
export PATH=$HOME/.local/bin:$PATH

virtualenv $LOCAL
source $LOCAL/bin/activate
mkdir -p $LOCAL/src
pip install pip --upgrade
pip install setuptools --upgrade

# Standard python dependencies
pip install --ignore-installed cython python-cjson 'numpy>=1.6.4'
SWIG_FEATURES="-cpperraswarn -includeall -I/usr/include/openssl" pip install M2Crypto

# Install lalsuite itself
cd $LOCAL/src/
git clone https://github.com/lscsoft/lalsuite.git
cd lalsuite
./00boot
./configure --prefix=$PWD/../../ --enable-swig-python \
--enable-swig-python --disable-lalstochastic --disable-lalxml \
--disable-lalinference --disable-laldetchar --disable-lalburst
make -j install
source $LOCAL/etc/lal-user-env.sh

pip install -e git+https://github.com/ligo-cbc/pycbc.git#egg=pycbc --process-dependency-links
cd $LOCAL

echo PEG_DIR=$PEG_DIR > source
echo PATH=$HOME/.local/bin:$PATH >> source
echo source $LOCAL/bin/activate >> source
echo source $LOCAL/etc/lal-user-env.sh >> source
echo source $LOCAL/etc/pycbc-user-env.sh >> source
echo 'PYTHONPATH=$PYTHONPATH:$PEG_DIR' >> source
chmod 755 source

cd $LOCAL/src/pycbc
python setup.py install

